
SUFFIXES = .cl

#
# We assume clang is downloaded under llvm tools directory.
#
CPP.Flags += -I$(LLVM_SRC_ROOT)/tools/clang/include \
             -I$(LLVM_OBJ_ROOT)/tools/clang/include

OCLGEN = $(ToolDir)/oclgen

BCCompile.OCL = $(LLVMCC) $(CPP.Flags) $(C.Flags) $(CFLAGS) $(CPPFLAGS) \
                $(TargetCommonOpts) $(CompileCommonOpts)
OCLGen = $(OCLGEN) -I $(call SYSPATH, $(PROJ_SRC_DIR)) \
	 -I $(call SYSPATH, $(PROJ_SRC_ROOT)/include)

# Provide rule sets for when dependency generation is enabled.
ifndef DISABLE_AUTO_DEPENDENCIES

$(ObjDir)/%.ll: %.cl $(ObjDir)/.dir $(BUILT_SOURCES) $(LLVMCXX)
	$(Echo) "Compiling $*.cl for $(BuildMode) build (bytecode)"
	$(Verb) if $(BCCompile.OCL) $(BC_DEPEND_OPTIONS) \
	                            $(LLVMCC_EMITIR_FLAG) \
                                    $< -o $(ObjDir)/$*.ll -S; \
                  $(BC_DEPEND_MOVEFILE)

# Provide alternate rule sets if dependencies are disabled.
else

$(ObjDir)/%.ll: %.cl $(ObjDir)/.dir $(BUILT_SOURCES) $(LLVMCXX)
	$(Echo) "Compiling $*.cl for $(BuildMode) build (bytecode)"
	$(BCCompile.OCL) $< -o $@ -S $(LLVMCC_EMITIR_FLAG)

endif

check-format::
	$(Verb) for dir in $(DIRS); do \
	          ($(MAKE) -C $$dir $@) || exit 1; \
	        done

check-format:: check-line-length-local check-for-tabs-local

RED_COLOR = '\033[1;31m'
RESET_COLOR = '\033[0m'

check-line-length-local:
	$(Echo) "Searching for overlength lines"
	$(Verb) for file in $(Sources); do \
	          src=$(PROJ_SRC_DIR)/$$file; \
	          if [ -f $$src ]; then \
		    awk -v file=$$file \
		        -v red_c=$(RED_COLOR) \
			-v reset_c=$(RESET_COLOR) \
			'/.{81}/ { printf("%s%s:%d:%s%s\n", \
			                  red_c, file ,NR, reset_c, $$0) }' \
			$$src; \
		  fi; \
		done

check-for-tabs-local:
	$(Echo) "Searching for tabs"
	$(Verb) for file in $(Sources); do \
	          src=$(PROJ_SRC_DIR)/$$file; \
	          if [ -f $$src ]; then \
		    awk -v file=$$file \
		        -v red_c=$(RED_COLOR) \
			-v reset_c=$(RESET_COLOR) \
			'/\t/ { printf("%s%s:%d:%s%s\n", \
                                       red_c, file ,NR, reset_c, $$0) }' \
			$$src; \
		  fi; \
		done
