##===- tools/OpenCRunCPUPasses/Makefile --------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = OpenCRunCPUPasses

LOADABLE_MODULE = 1

USEDLIBS = opencrunCPUPasses.a

include $(LEVEL)/Makefile.common
