##===- tools/OpenCRunCPUPasses/Makefile --------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = OpenCRunCPUPasses

LOADABLE_MODULE = 1

LLVMLIBS = clangBasic.a
USEDLIBS = opencrunCPUPasses.a opencrunUtil.a

include $(LEVEL)/Makefile.common
