##===- tools/OpenCRunPasses/Makefile -----------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = OpenCRunPasses

LOADABLE_MODULE = 1

LLVMLIBS = clangBasic.a
USEDLIBS = opencrunPasses.a opencrunUtil.a

include $(LEVEL)/Makefile.common
