##===- lib/Device/CPULib/Makefile --------------------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL = ../../..

#
# List all of the subdirectories that we will compile.
#
DIRS = BitCode InternalCall

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
