##===- lib/Device/CPULib/Makefile --------------------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL = ../../..

#
# Give the name of a library.
#
MODULE_NAME = opencrunCPULib

#
# Declare by-hand sources files, to get rid of LLVM building system.
#
SOURCES = WorkItem.cl Math.cl

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
