##===- lib/Device/CPULib/BitCode/Makefile ------------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL = ../../../..

#
# Give the name of a library.
#
MODULE_NAME = opencrunCPULib

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
