##===- tools/platform-query/Makefile -----------------------*- Makefile -*-===##

LEVEL = ../..

TOOLNAME = hardware-viewer

LINK_COMPONENTS = core
USEDLIBS = opencrunSystem.a

include $(LEVEL)/Makefile.common
