##===- unittests/Skel/Makefile -----------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL = ../..

#
# Name of the test.
#
TESTNAME = Skel

LINK_COMPONENTS = support

include $(LEVEL)/Makefile.config
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
