##===- bench/blocked-msquare/Makefile ----------------------*- Makefile -*-===##

LEVEL = ../..

#
# Name of the benchmark.
#
BENCHNAME = blocked-msquare

include $(LEVEL)/Makefile.config
include $(PROJ_SRC_ROOT)/bench/Makefile.bench
