##===- tools/Makefile --------------------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL = ..

#
# List all of the subdirectories that we will compile.
#
DIRS = libOpenCRun \
       OpenCRunPasses OpenCRunCPUPasses \
       platform-query hardware-viewer

include $(LEVEL)/Makefile.common
